Repository da-in/algorithm-study, pull requests merged in 2023-02, with the labels that each got.

#40 [23-02-01] hyuksoon.py
  Programmers - 고득점 Kit/[정렬] K번째수/hyuksoon.py
  Programmers - 고득점 Kit/[정렬] 가장 큰 수/hyuksoon.py
  Programmers - 고득점 Kit/[힙] 더 맵게/hyuksoon.py
Labels: heap, sort

#63 [23-02-06] kyuhyun.py
  Programmers - 고득점 Kit/[DFS-BFS] 타겟 넘버/kyuhyun.py
  Programmers - 고득점 Kit/[이분탐색] 입국심사/kyuhyun.py
Labels: dfs/bfs, binary search

#68 [23-02-07] seungyeon.py
  Programmers - 고득점 Kit/[그래프] 가장 먼 노드/seungyeon.py
Labels: dfs/bfs

#76 [23-02-08] kyuhyun.py
  Programmers - 고득점 Kit/[스택-큐] 기능개발/kyuhyun.py
  Programmers - 고득점 Kit/[해쉬] 전화번호 목록/kyuhyun.py
  Programmers - 고득점 Kit/[해시] 완주하지 못한 선수/kyuhyun.py
  Programmers - 고득점 Kit/[힙] 디스크 컨트롤러/kyuhyun.py
Labels: hash, stack/queue

#98 [23-02-14] seungyeon.py
  Programmers - 고득점 Kit/[DFS-BFS] 게임 맵 최단거리/seungyeon.py
  Programmers - 고득점 Kit/[DP] 정수 삼각형/seungyeon.py
  Programmers - 고득점 Kit/[그리디] 구명보트/seungyeon.py
  Programmers - 고득점 Kit/[완전탐색] 모의고사/seungyeon.py
Labels: DP

#105 [23-02-15] kyuhyun.py
  Programmers - 고득점 Kit/[DFS-BFS] 게임 맵 최단거리/kyuhyun.py
  Programmers - 고득점 Kit/[그리디] 구명보트/kyuhyun.py
Labels: dfs/bfs, greedy
